spring:
  datasource:
    url: jdbc:mysql://localhost:3306/manadatabase?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: pratham123
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl_auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
project:
  image: "images/"
